apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  project: default
  source: 
    path: monitoring/prometheus-deployment
    repoURL: "https://github.com/lordagam/Project-DevOps-devops-prod.online.git" 
    targetRevision: main
